name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: sawanoboly/action-set@master
      id: setter
      with:
        who-to-greet: Hello 
    - name: Run an env_time
      run: echo ${env_time}
    - name: Run an ENV_TIME
      run: echo ${ENV_TIME}
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
